default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PG_HOST'] %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  primary:
    <<: *default
    database: <%= ENV['PG_DATABASE'] %>

  queue:
    <<: *default
    database: <%= ENV['PG_DATABASE'] %>

  cache:
    <<: *default
    database: <%= ENV['PG_DATABASE'] %>

  connects_to:
    writing: primary
    reading: primary